export { idsInRect, rectsOverlap, selectOnly, toggleId } from './model/selection.model'
export type { CardRect, RectLike } from './model/selection.model'
export { useBoxSelection } from './composables/useBoxSelection'
export { useFolderSelection } from './composables/useFolderSelection'
export type { FolderSelection } from './composables/useFolderSelection'
